In [1]:
import numpy as np
b=np.array([[0,1,2],[3,4,5],[6,7,8]])
b
#print(b)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [2]:
b.ndim

2

In [3]:
b.shape

(3, 3)

In [4]:
len(b)

3

In [5]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [6]:
d=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [7]:
d.ndim

3

In [8]:
len(d)

2

In [9]:
d.shape

(2, 2, 2)

In [10]:
print(np.array(10))

10


In [11]:
c=np.zeros((1,2,3))
c

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [14]:
a=np.arange(0,101,25)
print(a)


[  0  25  50  75 100]


In [20]:
b=np.arange(0,9,2)
print(b)

[0 2 4 6 8]


In [23]:
b=b[:, np.newaxis]
a+b

array([[  0,  25,  50,  75, 100],
       [  2,  27,  52,  77, 102],
       [  4,  29,  54,  79, 104],
       [  6,  31,  56,  81, 106],
       [  8,  33,  58,  83, 108]])

In [1]:
if(a %2 ==0):
    count++
    return 0

    


sahil
